% Clean up script for Trajectory Follower with RoadRunner Scenario Example
%
% This script cleans up the TrajectoryFollowerWithRRScenarioTestBench model.
% It is triggered by the CloseFcn callback.
%
%   This is a helper script for example purposes and may be removed or
%   modified in the future.

%   Copyright 2021-2023 The MathWorks, Inc.

clear 'Tstep'
clear 'tau'
clear 'time_gap'
clear 'default_spacing'
clear 'max_ac'
clear 'min_ac'
clear 'max_steer'
clear 'min_steer'
clear 'PredictionHorizon'
clear 'v0_ego'
clear 'tau2'
clear 'max_dc'
clear 'm'
clear 'Iz'
clear 'Cf'
clear 'Cr'
clear 'lf'
clear 'lr'

clearBuses({...
    'BusActionComplete',...
    'BusActorActions',...
    'BusActorPose',...
    'BusActorRuntime',...
    'BusActorSpec',...
    'BusBoundingBox',...
    'BusDiagnostics',...
    'BusLaneChangeAction',...
    'BusPaintColor',...
    'BusPathAction',...
    'BusPathPointTiming',...
    'BusPathTarget',...
    'BusSpeedAction',...
    'BusTransitionDynamics',...
    'BusVehicleLocationOnLane',...
    'BusVehicleRuntime',...
    'BusVehicleSpec',...
    'BusWheelSpec',...
    'BusVehicleInfo',...
    'BusVehStates',...
    'BusWheelPoses'});

function clearBuses(buses)
matlabshared.tracking.internal.DynamicBusUtilities.removeDefinition(buses);
end